### PR TITLE
switched to qt5 / fix compilation on ubuntu 17.10

### PR DESCRIPTION
**Pull request by monotek**

### CODE REVIEW

**Comment by xlp0rk0lx** [comment]
Very well done, but i don't think update "master branch" for fix dependencies for Linux System not LTS will be a great "stable" solution in time

**Comment by xCuri0** [comment]
@monotek I tried compiling this on Arch Linux but it gives errors since this only supports OpenSSL 1.0 and Arch has 1.1 Can you update OpenSSL ?

**Comment by monotek** [comment]
No, I don't use arch, So I can't test.

**Comment by xCuri0** [comment]
@monotek I think you can install OpenSSL 1.1 on Ubuntu too

**Comment by monotek** [comment]
I think you can install OpenSSL 1.0 on Arch too.

**Comment by xCuri0** [comment]
@monotek OpenSSL 1.0 can be installed alongside 1.1 on Arch but I don't know how to get QMake to use it (guides on the internet only say how to do it with autotools)

**Pull request closed without merging**
